language: php

#notifications:
#    email:
#        recipients:
#            - dev@dmk-ebusiness.de
#        on_success: change
#        on_failure: always

php:
    - 5.6
    - 7.0
    - 7.1

env:
    - TYPO3_CORE="typo3/cms=^6.2.14"
    - TYPO3_CORE="typo3/cms=^7.6.0"
    - TYPO3_CORE="typo3/cms-=^8.7.0"
#    - TYPO3_CORE="typo3/cms-core=^9.6"

matrix:
    exclude:
        - php: 7.0
          env: TYPO3_CORE="typo3/cms=^6.2.14"
        - php: 7.1
          env: TYPO3_CORE="typo3/cms=^6.2.14"
        - php: 5.6
          env: TYPO3_CORE="typo3/cms=^8.7.0"

sudo: false

addons:
    apt:
        packages:
            - parallel

cache:
    directories:
        - $HOME/.composer/cache

before_install:
    - phpenv config-rm xdebug.ini
    - composer self-update
    - composer --version

before_script:
    - composer require "$TYPO3_CORE"
    # Restore composer.json
    - git checkout composer.json
    - export TYPO3_PATH_WEB=$PWD/.Build/Web

script:
    - >
        echo;
        echo "Running unit tests";
        .Build/bin/phpunit -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml Tests/Unit/PHP/
        # Only start the unittests!
        .Build/bin/phpunit --group unit -c .Build/vendor/nimut/testing-framework/res/Configuration/UnitTests.xml tests/

# disabled, because there are direct tx_rnbase::load calls in the files!
#  - >
#    echo;
#    echo "Running php lint";
#    find . -name \*.php ! -path "./.Build/*" | parallel --gnu php -d display_errors=stderr -l {} > /dev/null \;
